name: CI

on:
  push:
    branches:
      - main
  pull_request:


permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
#  lint:
#    name: Lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v6
#      - uses: actions/setup-python@v6
#        with:
#          python-version: '3.12'
#          cache: pip
#      - name: Install pre-commit
#        run: |
#          python -m pip install --upgrade pip
#          pip install pre-commit
#      - name: Run pre-commit
#        run: pre-commit run --all-files --show-diff-on-failure --color always

  tests:
    name: Tests (${{ matrix.os }} / py${{ matrix.python }})
#    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.10', '3.13']
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e ".[testing]"
      - name: Run pytest (POSIX)
        if: runner.os != 'Windows'
        run: pytest --maxfail=1 --disable-warnings
      - name: Run pytest (Windows)
        if: runner.os == 'Windows'
        run: pytest --maxfail=1 --disable-warnings -p no:faulthandler
